/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/NewZorrito-Web.glb --typescript 
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Retopo_Cuerpo: THREE.Mesh
    Retopo_Capa: THREE.Mesh
    Retopo_ojos: THREE.Mesh
    Retopo_Accesorio: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.ComponentProps<'group'>) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/NewZorrito-Web.glb') as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  // Autoplay the first animation found
  useEffect(() => {
    if (names.length > 0) {
      actions[names[0]]?.reset().fadeIn(0.5).play()
    }
  }, [actions, names])

  // Gentle floating/rotation animation
  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    if (group.current) {
      group.current.rotation.y = t * 0.5 // Continuous rotation (turn around)
      group.current.position.y = -0.2 + Math.sin(t * 1) * 0.1 // Floating effect
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Retopo_Cuerpo.geometry}
        material={materials.Material}
      />
      <mesh
        geometry={nodes.Retopo_Capa.geometry}
        material={materials['Material.001']}
      />
      <mesh
        geometry={nodes.Retopo_ojos.geometry}
        material={materials['Material.003']}
      />
      <mesh
        geometry={nodes.Retopo_Accesorio.geometry}
        material={materials['Material.002']}
      />
    </group>
  )
}

useGLTF.preload('/models/NewZorrito-Web.glb')